
-- PACIENTES: datos anidados como jsonb + ausencias
alter table pacientes add column if not exists ausencias integer not null default 0;
alter table pacientes add column if not exists dni text;
alter table pacientes add column if not exists tratamientos jsonb not null default '[]'::jsonb;
alter table pacientes add column if not exists pagos jsonb not null default '[]'::jsonb;
alter table pacientes add column if not exists odontograma jsonb not null default '{}'::jsonb;

alter table turnos add column if not exists paciente_id bigint;
alter table turnos add column if not exists es_sugerido boolean not null default false;
alter table turnos add column if not exists recurrente text;

-- CONFIG: arrays como jsonb, con defaults razonables
alter table config add column if not exists dias jsonb not null default '[1,2,3,4,5]'::jsonb;
alter table config add column if not exists bloqueados jsonb not null default '[]'::jsonb;
alter table config add column if not exists dra text not null default 'PERALTA PILAR';
alter table config add column if not exists desde text not null default '09:00';
alter table config add column if not exists hasta text not null default '18:00';

-- IDs: la app no envía estos valores; la base debe generarlos.
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'pacientes'
      and column_name = 'id'
      and is_identity = 'YES'
  ) then
    alter table public.pacientes alter column id add generated by default as identity;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'turnos'
      and column_name = 'id'
      and is_identity = 'YES'
  ) then
    alter table public.turnos alter column id add generated by default as identity;
  end if;
end;
$$;

select setval(
  pg_get_serial_sequence('public.pacientes', 'id'),
  coalesce((select max(id) from public.pacientes), 0) + 1,
  false
);

select setval(
  pg_get_serial_sequence('public.turnos', 'id'),
  coalesce((select max(id) from public.turnos), 0) + 1,
  false
);

-- CONFIG: crea una configuración inicial para cada usuario nuevo.
-- Requiere que config.user_id tenga una restricción UNIQUE.
create or replace function public.crear_config_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.config (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.crear_config_usuario();
